version: "3"

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    environment:
      SECRET_KEY: clave_secreta_para_generar_tokens_jwt
      DATABASE_URL: postgresql://postgres:cadena12@db:5432/bdrutas
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data: